volumes:
  db_data:
    external: true
services:
  fastapi:
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      CORS_HOSTS: ${CORS_HOSTS}
      DB_URL: ${DB_URL}
      WAIT_HOSTS: db:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      PORT: 8000
    build:
      context: api
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  next-frontend:
    image: node:lts-bullseye
    command: bun --bun run dev
    working_dir: /app
    volumes:
      - ./next-frontend:/app
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      HOST_OS: ${HOST_OS}
