volumes:
  db_data:
    external: true
services:
  fastapi:
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      CORS_HOSTS: ${CORS_HOSTS}
      DB_URL: ${DB_URL}
      WAIT_HOSTS: db:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      PORT: 8000
      WORKOS_API_KEY: ${WORKOS_API_KEY}
      WORKOS_CLIENT_ID: ${WORKOS_CLIENT_ID}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      WORKOS_REDIRECT_URI: ${WORKOS_REDIRECT_URI}
    build:
      context: api
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  client:
    build:
      context: ./client
      dockerfile: dockerfile.dev
    depends_on:
      - fastapi
    volumes:
      - ./client:/app
    env_file:
      - ./client/.env.local
    ports:
      - 3000:3000

  db:
    image: postgres:14.5-bullseye
    volumes:
      - db_data:/var/lib/postgresql/db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "15432:5432"
